# Generated by Django 5.0 on 2023-12-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('new', 'yangi'), ('completed', 'yakunlangan')], default='new', max_length=100),
        ),
    ]
